#!/usr/bin/env python3
"""Write the AUR package nagram-desktop-bin for a released Linux archive.

Writes PKGBUILD and .SRCINFO from the one description below, so the two
cannot disagree. The package installs the release archive as it is: the
binary to /usr/bin/Nagram, Nagram/share to /usr/share, and a marker that
switches the built-in updater off, since pacman updates the package.
"""

import argparse
import hashlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import release_version

NAME = "nagram-desktop-bin"
DESCRIPTION = "Independent Telegram client based on Telegram Desktop (release binary)"
URL = "https://github.com/NextAlone/Nagram-qt"
LICENSE = "GPL-3.0-or-later WITH OpenSSL-exception"
MAINTAINER = "NextAlone <https://github.com/NextAlone>"
# gtk3, libx11, libxcb, wayland and dbus are loaded at run time, ldd does not show them.
DEPENDS = (
    "cairo",
    "dbus",
    "fontconfig",
    "freetype2",
    "glib2",
    "glibc",
    "gtk3",
    "hicolor-icon-theme",
    "libx11",
    "libxcb",
    "pango",
    "wayland",
)
OPTDEPENDS = (
    ("webkit2gtk-4.1", "bots and web apps inside the client"),
    ("xdg-desktop-portal", "file dialogs of the desktop environment"),
    ("libpulse", "sound through PulseAudio or PipeWire"),
    ("alsa-lib", "sound through ALSA"),
    ("libpipewire", "screen sharing on Wayland"),
    ("geoclue", "sharing the current location"),
    ("libva", "hardware video decoding"),
)
PROVIDES = "nagram-desktop"
OPTIONS = ("!strip", "!debug")
ARCHIVE = "Nagram-{version}-linux-{arch}.tar.xz"
SOURCE = "{archive}::{url}/releases/download/v{version}/{archive}"
PACKAGE = """\
package() {
	install -Dm755 Nagram/Nagram "$pkgdir/usr/bin/Nagram"
	install -d "$pkgdir/usr/share"
	cp -r --no-preserve=ownership Nagram/share/. "$pkgdir/usr/share/"

	# pacman updates this copy, so the built-in updater is switched off.
	install -d "$pkgdir/usr/share/NagramDesktop/externalupdater.d"
	echo /usr/bin/Nagram > "$pkgdir/usr/share/NagramDesktop/externalupdater.d/$pkgname.conf"
}
"""


class AurError(Exception):
    pass


def pkgbuild(version, sha256):
    optional = "".join(f"\t'{name}: {text}'\n" for name, text in OPTDEPENDS)
    source = SOURCE.format(
        archive=ARCHIVE.format(version="$pkgver", arch="$CARCH"), url="$url", version="$pkgver"
    )
    return (
        f"# Maintainer: {MAINTAINER}\n"
        f"# Generated by tools/nagram/aur_package.py in {URL}\n\n"
        f"pkgname={NAME}\n"
        f"pkgver={version}\n"
        "pkgrel=1\n"
        f'pkgdesc="{DESCRIPTION}"\n'
        "arch=(x86_64)\n"
        f'url="{URL}"\n'
        f"license=('{LICENSE}')\n"
        f"depends=({' '.join(DEPENDS)})\n"
        f"optdepends=(\n{optional})\n"
        f"provides=({PROVIDES})\n"
        f"conflicts=({PROVIDES})\n"
        f"options=({' '.join(OPTIONS)})\n"
        f'source=("{source}")\n'
        f"sha256sums=('{sha256}')\n\n" + PACKAGE
    )


def srcinfo(version, sha256):
    """What 'makepkg --printsrcinfo' prints for the PKGBUILD above."""
    archive = ARCHIVE.format(version=version, arch="x86_64")
    fields = [("pkgdesc", DESCRIPTION), ("pkgver", version), ("pkgrel", "1"), ("url", URL)]
    fields += [("arch", "x86_64"), ("license", LICENSE)]
    fields += [("depends", name) for name in DEPENDS]
    fields += [("optdepends", f"{name}: {text}") for name, text in OPTDEPENDS]
    fields += [("provides", PROVIDES), ("conflicts", PROVIDES)]
    fields += [("options", option) for option in OPTIONS]
    fields += [("source", SOURCE.format(archive=archive, url=URL, version=version))]
    fields += [("sha256sums", sha256)]
    lines = [f"pkgbase = {NAME}"] + [f"\t{key} = {value}" for key, value in fields]
    return "\n".join(lines) + f"\n\npkgname = {NAME}\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--archive", required=True, help="the released Linux archive")
    parser.add_argument("--out", required=True, help="directory for PKGBUILD and .SRCINFO")
    parser.add_argument("--root", default=release_version.ROOT)
    args = parser.parse_args(argv)
    try:
        root = Path(args.root)
        tag = release_version.release_tag(root)
        if tag.endswith("-beta"):
            raise AurError(f"{tag} is a beta: only stable releases go to the AUR")
        version = tag[1:]
        archive = Path(args.archive)
        expected = ARCHIVE.format(version=version, arch="x86_64")
        if archive.name != expected:
            raise AurError(f"{archive} is not {expected}, the archive of {tag}")
        try:
            sha256 = hashlib.sha256(archive.read_bytes()).hexdigest()
        except OSError as error:
            raise AurError(f"cannot read {archive}: {error}") from error
    except (AurError, release_version.VersionError) as error:
        print(error, file=sys.stderr)
        return 1
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    (out / "PKGBUILD").write_text(pkgbuild(version, sha256), encoding="utf-8")
    (out / ".SRCINFO").write_text(srcinfo(version, sha256), encoding="utf-8")
    print(f"{NAME} {version}-1 written to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
